### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by alonewolfx2** [eadf/esp8266_pcd8544#1]
firstly I wish to say thank you for your work.Can i use gpio0 and gpio 2 instead of gpio4-5? and can you port  hc-sr04 library for esp8266 :) here is github link for library https://github.com/JRodrigoTech/Ultrasonic-HC-SR04

**Comment by eadf** [comment]
Ok, I've made the pin assignments configurable. You just set the pins you want to use in the setting struct.

I actually own a hc-sr04 so i'll look into making a port for it. Thanks for the idea. 
No promises though.

**Comment by alonewolfx2** [comment]
Thank you very much.

**Comment by alonewolfx2** [comment]
any progress for hc-sr04 :)

**Comment by eadf** [comment]
Here you go: github.com/eadf/esp8266-ping :)
It's an initial rough version, but it seems to work. Feel free to test
