### ISSUE TITLE
compile on mac

### ISSUE THREAD

**Issue by eliabieri** [eadf/esp8266_pcd8544#4]
is there a way to compile this on a mac?
I tried with the makefile.mac from the esp_mqtt repo but i got a lot of errors.

**Comment by eadf** [comment]
It should be possible. My mac is not up for the task right now, but i can test it later.
........
Ok, i can compile and flash this project with my mac.
Using the "new" makefile.mac (identical to makefile.linux - only the ESPPORT default value differ)

**Comment by eliabieri** [comment]
I tried your makefile and it didnt work for me.
I think its because we have not the same sdk setups.
I installed my sdk with this tutorial: http://tuanpm.net/post/109019196894/esp8266-development-kit-on-mac-os-yosemite-and
I changed your makefile to work with my setup.
If you want it, I could make a PR

**Comment by eliabieri** [comment]
I tried your makefile and it didnt work for me.
I think its because we have not the same sdk setups.
I installed my sdk with this tutorial: http://tuanpm.net/post/109019196894/esp8266-development-kit-on-mac-os-yosemite-and
I changed your makefile to work with my setup.
If you want it, I could make a PR

**Comment by eliabieri** [comment]
I tried your makefile and it didnt work for me.
I think its because we have not the same sdk setups.
I installed my sdk with this tutorial: http://tuanpm.net/post/109019196894/esp8266-development-kit-on-mac-os-yosemite-and
I changed your makefile to work with my setup.
If you want it, I could make a PR

**Comment by eliabieri** [comment]
I tried your makefile and it didnt work for me.
I think its because we have not the same sdk setups.
I installed my sdk with this tutorial: http://tuanpm.net/post/109019196894/esp8266-development-kit-on-mac-os-yosemite-and
I changed your makefile to work with my setup.
If you want it, I could make a PR

**Comment by eadf** [comment]
If it's only the paths that differ you can always override the default paths in the Makefile with your local environment. 

shell:

```
export SDK_BASE=/esptools/esp-open-sdk/sdk
export PATH=$SDK_BASE/bin:$PATH # or wherever

make -f Makefile.mac
```

I installed my mac sdk with https://github.com/pfalcon/esp-open-sdk. Really easy, once you execute the little 'fix' described here: https://github.com/pfalcon/esp-open-sdk/issues/11

But maybe it was more than the paths that had to be changed?

---

I've updated the Readme on how to build the project.
